### ISSUE TITLE
anyOf Method 

### ISSUE THREAD

**Issue by gherkins** [gherkins/regexpbuilderphp#1]
adrianmiu via reddit 

I would change
`->eitherFind("png")->orFind("jpg")->orFind("gif")`
to something like
`->anyOf(array('png', 'jpg', 'gif'))`
or something to that extent

**Comment by ELD** [comment]
If you don't mind accepting PRs/haven't begun on this suggestion yet, I'll fork the repo today and see what I can do with this enhancement.

**Comment by gherkins** [comment]
:+1:

**Comment by ELD** [comment]
Sounds good. Also, would you like to keep the existing API or replace it completely with anyOf()?

**Comment by gherkins** [comment]
...maybe just add it as a shortcut and call `eitherFind` & `orFind` internally ?

Both methods also take an instance of `RegExpBuilder` to combine expressions...

**Comment by ELD** [comment]
That’s a pretty good idea. I didn’t even think of that but it would definitely make a lot more sense.
