### ISSUE TITLE
How to get everything between tags

### ISSUE THREAD

**Issue by TomasVotruba** [gherkins/regexpbuilderphp#10]
I need to get something between to tag (match, but excluding). How to do so?

I've stared with:

``` php
$surroundingTag = (new RegExpBuilder)->startOfInput()
    ->find('<p>')
    ->anything() // I need this content
    ->find('</p>')
    ->endOfInput()
    ->getRegExp();
```

**Comment by gherkins** [comment]
...i'm afraid that exceeds the possibilities of the library,
as it builds on single expression with no support for matching parts of it as single results.

as in `/<tag>(.*?)<\/tag>/`
