### ISSUE TITLE
Class 'Gherkins\RegExpBuilderPHP\RegExpBuilder' not found

### ISSUE THREAD

**Issue by Fshamri** [gherkins/regexpbuilderphp#11]
I just downloaded your repo using composer require gherkins/regexpbuilderphp and started soing some tests as suggested by you. i have created new test.php file under regexpbuilderphp folder 

```
<?php
namespace Gherkins\RegExpBuilderPHP;


$builder = new \Gherkins\RegExpBuilderPHP\RegExpBuilder();

$regExp = $builder
    ->startOfInput()
    ->exactly(4)->digits()
    ->then("_")
    ->exactly(2)->digits()
    ->then("_")
    ->min(3)->max(10)->letters()
    ->then(".")
    ->anyOf(array("png", "jpg", "gif"))
    ->endOfInput()
    ->getRegExp();

//true
$regExp->matches("2020_10_hund.jpg");
$regExp->matches("2030_11_katze.png");
$regExp->matches("4000_99_maus.gif");

//false
$regExp->matches("123_00_nein.gif");
$regExp->matches("4000_0_nein.pdf");
$regExp->matches("201505_nein.jpg");
```

but i am getting error saying: 

```
Fatal error: Class 'Gherkins\RegExpBuilderPHP\RegExpBuilder' not found in    C:\wamp\www\gherkins\regexpbuilderphp\src\test.php on line 5
```

 can you please help.

thanks

**Comment by electricjones** [comment]
you have to `require "vendor/autoload.php"` after the `namespace` to use composer autoloading.

**Comment by electricjones** [comment]
Or in the case of your `test.php` file being there, probably need to `require "../vendor/autoload.php"`.

This autoload file is what allow you to use classes without having to load them manually. See https://getcomposer.org/ or https://laracasts.com/series/laravel-5-from-scratch/episodes/1 for a good video introduction to composer.

**Comment by Fshamri** [comment]
Fixed ... Thanks a lot for your efforts
