### ISSUE TITLE
There is no way to set the "s" flag

### ISSUE THREAD

**Issue by akond** [gherkins/regexpbuilderphp#12]
Is that a feature or you've just forgotten?

**Comment by younes0** [comment]
I'm not sure what you mean but it seems to me that whitespace() is what you are referring to.
Still I think it's broken, replacing `then(' ')` by `whitespace()` doesn't work

**Comment by gherkins** [comment]
I think it's simply not implemented yet, 
as this was ported from JS, where the s flag does not exist afaik...

**Comment by TomasVotruba** [comment]
Could you send a PR @akond ?
