### ISSUE TITLE
Missing maintainer

### ISSUE THREAD

**Issue by TomasVotruba** [gherkins/regexpbuilderphp#22]
Is there some maintainer for this package? I'd be happy to help to move it forward and upgrade to current PHP versions

**Comment by gherkins** [comment]
Thanks,
development hasn't been that active, since it was supposed to be just a fork of https://github.com/thebinarysearchtree/regexpbuilderjs and was somewhat "finished" then...

I'll try to fix anything coming up, though.
Any contributions are appreciated!

Cheers

**Comment by TomasVotruba** [comment]
@gherkins Thanks for the answer. I would be happy to contribute.

 Would you be open to bump current dev version to PHP 7.0?
 
Since it's finished and PHP 7+ are only actively supported versions (http://php.net/supported-versions.php),  we could make use of great script types.

**Comment by gherkins** [comment]
yes, definitely.
dev-master & 0.8+ could be php7 only. 
would be 0.7 for legacy php support then...

**Comment by TomasVotruba** [comment]
That's great! :+1:  

Shall I send the PHP 7 PR then?

**Comment by gherkins** [comment]
yes, sure !
That would be great 🥇

**Comment by TomasVotruba** [comment]
I'm on it! :construction_worker_man: 

Done via https://github.com/gherkins/regexpbuilderphp/pull/25
