### ISSUE TITLE
rename "test" method name to something like "matches", or "doesMatch"

### ISSUE THREAD

**Issue by gherkins** [gherkins/regexpbuilderphp#3]
iAMthePRONY via reddit 

> i would've change the "test" method name to something like "matches", or "doesMatch"

**Comment by gherkins** [comment]
yep, that does sound better.
got this in the first place from emulating https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

**Comment by TomasVotruba** [comment]
:+1:

**Comment by gherkins** [comment]
so ->matches() it is...

test() still exists as an alias, but is marked deprecated

**Comment by TomasVotruba** [comment]
Great!
