### ISSUE TITLE
Match any 0+ of lineBreaks

### ISSUE THREAD

**Issue by TomasVotruba** [gherkins/regexpbuilderphp#9]
Update: found a solution, is it proper?

I would like to match these cases:

``` html
- <code>hello</code>
- <code>hello
</code>
```

So I've created builder like this:

``` php
$surroundingTagRegExpWithLineBreaks = (new RegExpBuilder)->startOfInput()
    ->find(sprintf('<%s', $tag))
    ->anything()
    ->min(0)->lineBreaks()
    ->find(sprintf('</%s>', $tag))
    ->endOfInput()
    ->getRegExp();

```

I'd expect `->min(0)->lineBreaks()` to compatible with `->any()->lineBreaks()`. But it isn't.

**Comment by gherkins** [comment]
that's what I would have suggested, too.

I'm not quite happy with the any/anything/maybe methods myself.
...for sure there's room for improvements ;)

**Comment by TomasVotruba** [comment]
I'd change implementation of `any()` from:

``` php
return $this->exactly(1)->ofAny();
```

to

``` php
return $this->min(0)->ofAny();
```

Any should mean 0/1+, full spectrum.

**Comment by TomasVotruba** [comment]
Ping
